server:
  port: 9090

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/v1/users/**, /api/v1/rooms/**
        - id: message-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/v1/messages/**
        - id: search-service
          uri: http://localhost:8084
          predicates:
            - Path=/api/v1/search/**, /api/v1/search
        - id: websocket-service
          uri: http://localhost:8083
          predicates:
            - Path=/ws/**
        - id: media-service
          uri: http://localhost:8085
          predicates:
            - Path=/api/v1/media/**
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/chat-realm
